### ISSUE TITLE
Corretto uses JDK instead of JRE, is this because Corretto does not provide a JRE for Java 21?

### ISSUE THREAD

**Issue by crackthecodeabhi** [paketo-buildpacks/amazon-corretto#308]
Hi, i am trying to add Java 21 to the project, but this build pack is unable to get JRE, instead fallsback to JDK

## Expected Behavior

It should download JRE 21 instead of JDK 21
## Current Behavior

Downloads JDK 21 instead of JRE, and complains no valid JRE available
## Steps to Reproduce

1. set BP_JVM_VERSION to 21 and build image
### Logs
 Using Java version 21 from BP_JVM_VERSION
    [creator]       **No valid JRE available, providing matching JDK instead. Using a JDK at runtime has security implications.**
    [creator]       Corretto JDK 21.0.1: Contributing to layer
    [creator]         Downloading from https://corretto.aws/downloads/resources/21.0.1.12.1/amazon-corretto-21.0.1.12.1-linux-x64.tar.gz
    [creator]         Verifying checksum
    [creator]         Expanding to /layers/paketo-buildpacks_amazon-corretto/jdk

## Motivations

Was trying to use Java 21 JRE in my project.

**Comment by dmikusa** [comment]
Yes, that's correct. The upstream project does not provide JREs so one is not available, at least the last time I looked. If anything has changed there, please let us know and we can start shipping them. Thanks!

**Comment by crackthecodeabhi** [comment]
thanks, that helps @dmikusa, will look into it
