### ISSUE TITLE
Corretto 23 availability

### ISSUE THREAD

**Issue by audio-engineer** [paketo-buildpacks/amazon-corretto#380]
When will Corretto 23 be available as a buildpack? It has had GA for a while now and I would love to use it in one of my projects.

## Possible Solution

Let me know if I can help you by opening a pull request. I didn't check the contribution documentation yet, but I could try to add 23.

**Comment by dmikusa** [comment]
Released: https://github.com/paketo-buildpacks/amazon-corretto/releases/tag/v8.6.0

**Comment by audio-engineer** [comment]
@dmikusa Awesome! Thanks.
