### ISSUE TITLE
Provide ability to use custom URL for JDK and JVMKill download

### ISSUE THREAD

**Issue by jreznot** [paketo-buildpacks/amazon-corretto#93]
## What happened?

* What were you attempting to do?

I want to have network independent build of Docker images on CI of my company.
Please provide a config key to set base URL for JDK downloading.

* What did you expect to happen?

There should be a way to specify base URL to download JDK from a server inside the company. I want to have all dependencies cached to be able to build apps even if Amazon services are offline. Maven libraries are cached inside my company using Maven server that caches every library I use in apps.

1. Extract the attached project
2. Run `./gradlew bootBuildImage`

Demo project with Spring Boot and Gradle:
[demo-buildpack-image.zip](https://github.com/paketo-buildpacks/amazon-corretto/files/6937168/demo-buildpack-image.zip)

* What was the actual behavior? Please provide log output, if possible.

The build pack always downloads JDK from `https://corretto.aws/downloads/` and `JVMKill` from `https://github.com/cloudfoundry/jvmkill/`:

```
    [creator]       Corretto JDK 11.0.12: Contributing to layer
    [creator]         Downloading from https://corretto.aws/downloads/resources/11.0.12.7.1/amazon-corretto-11.0.12.7.1-linux-x64.tar.gz
    [creator]         Verifying checksum
    [creator]         Expanding to /layers/paketo-buildpacks_amazon-corretto/jdk
    [creator]       JVMKill Agent 1.16.0: Contributing to layer
    [creator]         Downloading from https://github.com/cloudfoundry/jvmkill/releases/download/v1.16.0.RELEASE/jvmkill-1.16.0-RELEASE.so
    [creator]         Verifying checksum
    [creator]         Copying to /layers/paketo-buildpacks_amazon-corretto/jvmkill
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

Spring Boot 2.5 BootBuildImage Gradle task.

* What buildpacks are you using? Please include versions.

```
tasks.withType<BootBuildImage> {
  builder = "gcr.io/paketo-buildpacks/builder:base"
  buildpacks = listOf(
    "gcr.io/paketo-buildpacks/amazon-corretto:latest",
    "gcr.io/paketo-buildpacks/executable-jar:latest",
    "gcr.io/paketo-buildpacks/spring-boot:latest",
  )
  environment = mapOf("BP_JVM_VERSION" to "11.0.12")
}
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

```
gcr.io/paketo-buildpacks/builder:base
```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist
* [X] I have included log output.
* [X] I have included steps for reproduction.

**Comment by jreznot** [comment]
It seems that the required configuration is described in
https://paketo.io/docs/reference/configuration/#building-behind-a-firewall

**Comment by dmikusa-pivotal** [comment]
> It seems that the required configuration is described in
> https://paketo.io/docs/reference/configuration/#building-behind-a-firewall

Correct. 

Please do let me know if you have any feedback on this process. We have been having some discussions about potentially making some changes. At the moment, it can be painful to remap a log of dependencies. In addition, you can only remap dependencies that exist in buildpack.toml, you cannot change versions. If you're hitting any limits with the existing support, feel free to reach out here or in a new issue. Thanks!
